<?php

namespace Recca0120\LaravelErd\Tests\Console\Commands;

use Illuminate\Support\Facades\File;
use Recca0120\LaravelErd\Tests\TestCase;

class LaravelErdCommandTest extends TestCase
{
    private string $storagePath;

    private string $file = 'actual_artisan.svg';

    protected function setUp(): void
    {
        parent::setUp();
        $this->storagePath = realpath(__DIR__ . '/../../fixtures');
        $this->app['config']->set('laravel-erd.storage_path', $this->storagePath);
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        File::delete($this->storagePath . '/' . $this->file);
    }

    public function test_generate_svg(): void
    {
        $this->artisan('laravel-erd', $this->givenParameters($this->file))->assertSuccessful();

        $contents = file_get_contents($this->storagePath . '/' . $this->file);
        self::assertStringContainsString('<!-- cars -->', $contents);
        self::assertStringContainsString('<!-- phones&#45;&#45;users -->', $contents);
    }

    public function test_command_not_exists(): void
    {
        $this->app['config']->set('laravel-erd.er.erd-go', '/bin/erd-go');

        $this->artisan('laravel-erd', $this->givenParameters($this->file))->assertFailed();
    }

    private function givenParameters(string $file): array
    {
        return ['file' => $file, '--directory' => $this->storagePath];
    }
}
